/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto.pkg2.edd;

import Estructuras.Matriz;
import java.awt.GridLayout;
import java.awt.Image;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.net.URL;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.BoxLayout;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author Luis
 */
public class Ventana extends javax.swing.JFrame {
    Matriz aux;
    public String nombreP,carpetaaux;
    public String[] auxC,auxA;
    public int corX,corY,cantC;
    /**
     * Creates new form Ventana
     */
    public Ventana(Matriz raiz) {
        initComponents();
        aux=raiz;
        nombreP="/";
        jPanel3.setLayout(null);
        pintarCarpetas(nombreP);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Crear");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Modificar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Eliminar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Subir");

        jLabel1.setText("Carpetas");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(50, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(19, 19, 19)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addGap(18, 18, 18)
                .addComponent(jButton4)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jButton5.setText("Crear");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Modificar");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("Eliminar");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setText("Subir");

        jLabel2.setText("Archivos");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(25, 25, 25)
                .addComponent(jButton5)
                .addGap(18, 18, 18)
                .addComponent(jButton6)
                .addGap(18, 18, 18)
                .addComponent(jButton7)
                .addGap(18, 18, 18)
                .addComponent(jButton8)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        jTextField1.setText("/");

        jButton9.setText("Entrar");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton10.setText("Ir");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 455, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(14, 14, 14)
                                .addComponent(jButton10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton9, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE))
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton9)
                            .addComponent(jButton10))
                        .addGap(18, 18, 18)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        int contador=0;
        while(corX>100){
            corX=corX-101;
            contador+=1;
        }
        while(corY>50){
            corY=corY-60;
            contador+=6;
        }
        contador=contador-cantC;
        String sus=auxA[contador];
        if (sus.equals("/")||sus.equals("raiz")) {
            
        }else{
            //System.out.println(sus);
            int p=aux.buscar_fila(nombreP);
            aux.borrar(aux.buscar_fila(p), sus);
            jPanel3.removeAll();
            pintarCarpetas(nombreP);
        }
        String ArchivoNuevo = JOptionPane.showInputDialog("Escribe nombre del archivo");
        Date date = new Date();
        DateFormat hourdateFormat = new SimpleDateFormat("HH:mm:ss dd/MM/yyyy");
        String time = "Hora y fecha: " + hourdateFormat.format(date);
        String[] parte = ArchivoNuevo.split("\\.");
        int p=aux.buscar_fila(nombreP);
        aux.agregarAVL(parte[0], jTextArea1.getText(), parte[1], time,aux.buscar_fila(p));
        pintarCarpetas(nombreP);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String carpetaNueva = JOptionPane.showInputDialog("Escribe nombre de carpeta");
        Date date = new Date();
        DateFormat hourdateFormat = new SimpleDateFormat("HH:mm:ss dd/MM/yyyy");
        String time = "Hora y fecha: " + hourdateFormat.format(date);
        aux.insertar(new Carpeta(carpetaNueva,time),aux.buscar_fila(nombreP));
        pintarCarpetas(nombreP);
        aux.mostrar();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        int contador=0;
        while(corX>100){
            corX=corX-101;
            contador+=1;
        }
        while(corY>50){
            corY=corY-60;
            contador+=6;
        }
        nombreP=auxC[contador];
        if (jTextField1.getText().equals("/")) {
            jTextField1.setText(jTextField1.getText()+nombreP);
        }else{
            jTextField1.setText(jTextField1.getText()+"/"+nombreP);
        }
        jPanel3.removeAll();
        pintarCarpetas(nombreP);
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        int contador=0;
        while(corX>100){
            corX=corX-101;
            contador+=1;
        }
        while(corY>50){
            corY=corY-60;
            contador+=6;
        }
        String sus=auxC[contador];
        if (sus.equals("/")||sus.equals("raiz")) {
            
        }else{
            System.out.println("borrar");
            aux.borrar(sus);
            jPanel3.removeAll();
            pintarCarpetas(nombreP);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int contador=0;
        while(corX>100){
            corX=corX-101;
            contador+=1;
        }
        while(corY>50){
            corY=corY-60;
            contador+=6;
        }
        String sus=auxC[contador];
        if (sus.equals("/")||sus.equals("raiz")) {
            
        }else{
            System.out.println("modificar");
            String carpetaNueva = JOptionPane.showInputDialog("Escribe nombre de carpeta");
            aux.modificar(sus, carpetaNueva);
            jPanel3.removeAll();
            pintarCarpetas(nombreP);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        if (!jTextField1.getText().equals("/")) {
            String[] aux=jTextField1.getText().split("/");
            nombreP=aux[aux.length-1];
            jPanel3.removeAll();
            pintarCarpetas(nombreP);
        }else{
            nombreP="/";
            jPanel3.removeAll();
            pintarCarpetas(nombreP);
        }
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        String ArchivoNuevo = JOptionPane.showInputDialog("Escribe nombre del archivo");
        Date date = new Date();
        DateFormat hourdateFormat = new SimpleDateFormat("HH:mm:ss dd/MM/yyyy");
        String time = "Hora y fecha: " + hourdateFormat.format(date);
        String[] parte = ArchivoNuevo.split("\\.");
        int p=aux.buscar_fila(nombreP);
        aux.agregarAVL(parte[0], jTextArea1.getText(), parte[1], time,aux.buscar_fila(p));
        pintarCarpetas(nombreP);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        int contador=0;
        while(corX>100){
            corX=corX-101;
            contador+=1;
        }
        while(corY>50){
            corY=corY-60;
            contador+=6;
        }
        contador=contador-cantC;
        String sus=auxA[contador];
        if (sus.equals("/")||sus.equals("raiz")) {
            
        }else{
            //System.out.println(sus);
            int p=aux.buscar_fila(nombreP);
            aux.borrar(aux.buscar_fila(p), sus);
            jPanel3.removeAll();
            pintarCarpetas(nombreP);
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
            }
        });
    }
    
    public void pintarCarpetas(String padre){
        int gX=0,gY=0;
        cantC=0;
        if (!aux.nombresC(padre).equals(" /;")&&!aux.nombresC(padre).equals("")) {
            jPanel3.removeAll();
            String[] partes=aux.nombresC(padre).split(";");
            JLabel[] labels=new JLabel[partes.length];
            int x=0;
            int y =0;
            cantC=partes.length;
            for (int i = 0; i < partes.length; i++) {
                labels[i]=new JLabel();
                if (partes[i]!=null && labels[i]!=null) {
                    //System.out.println("entra");
                    Image img= new ImageIcon(getClass().getResource("/Imagenes/carpeta.png")).getImage();
                    Image img2=img.getScaledInstance(40, 40, Image.SCALE_SMOOTH);
                    ImageIcon icon =new ImageIcon(img2);
                    //String path = "/Imagenes/carpeta.png";  
                    //URL url = this.getClass().getResource(path);  
                    //ImageIcon icon = new ImageIcon(url);  
                    labels[i].setIcon(icon);
                    labels[i].setText(partes[i]);
                    labels[i].setBounds(x,y,100,50);
                    labels[i].setVisible(true);
                    jPanel3.add(labels[i]); 
                    x+=101;
                    if (x>605) {
                        x=0;
                        y+=60;
                    }
                }
            }
            gX=x;
            gY=y;
            pintarArchivos(nombreP,gX,gY);
            jPanel3.repaint();
            auxC=partes;
        }else{
            jPanel3.removeAll();
            pintarArchivos(nombreP,gX,gY);
            jPanel3.repaint();
        }
        jPanel3.addMouseListener(new MouseListener() {
                        @Override
                        public void mouseClicked(MouseEvent e) {
                            corX =e.getPoint().x;
                            corY =e.getPoint().y;
                            //System.out.println(e.getPoint().x);
                            //System.out.println(e.getPoint().y);
                        }

                        @Override
                        public void mousePressed(MouseEvent e) {
                            
                        }

                        @Override
                        public void mouseReleased(MouseEvent e) {
                            
                        }

                        @Override
                        public void mouseEntered(MouseEvent e) {
                            
                        }

                        @Override
                        public void mouseExited(MouseEvent e) {
                            
                        }
                    });
    }
    
    public void pintarArchivos(String padre,int x,int y){
        int p=aux.buscar_fila(nombreP);
        if (!aux.nombresA(aux.buscar_fila(p)).equals("")) {
            String[] partes=aux.nombresA(aux.buscar_fila(p)).split(";");
            JLabel[] labels=new JLabel[partes.length];
            for (int i = 0; i < partes.length; i++) {
                labels[i]=new JLabel();
                if (partes[i]!=null && labels[i]!=null) {
                    //System.out.println("entraArchivo");
                    Image img= new ImageIcon(getClass().getResource("/Imagenes/logo.png")).getImage();
                    Image img2=img.getScaledInstance(40, 40, Image.SCALE_SMOOTH);
                    ImageIcon icon =new ImageIcon(img2);
                    //String path = "/Imagenes/carpeta.png";  
                    //URL url = this.getClass().getResource(path);  
                    //ImageIcon icon = new ImageIcon(url);  
                    labels[i].setIcon(icon);
                    labels[i].setText(partes[i]);
                    labels[i].setBounds(x,y,100,50);
                    labels[i].setVisible(true);
                    jPanel3.add(labels[i]); 
                    x+=101;
                    if (x>605) {
                        x=0;
                        y+=60;
                    }
                }
            }
            auxA=partes;
        }
    
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
