/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto.pkg2.edd;

import Estructuras.Matriz;
import Reportes.ReporteArbol;
import Reportes.ReporteGrafo;
import Reportes.ReporteMatriz;
import java.awt.GridLayout;
import java.awt.Image;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.net.URL;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BoxLayout;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import static proyecto.pkg2.edd.Proyecto2EDD.bitacora;
import static proyecto.pkg2.edd.Proyecto2EDD.tablaha;

/**
 *
 * @author Luis
 */
public class Ventana extends javax.swing.JFrame {
    Matriz aux;
    public String nombreP,carpetaaux,usuario;
    public String[] auxC,auxA;
    public int corX,corY,cantC;
    /**
     * Creates new form Ventana
     */
    public Ventana(Matriz raiz,String nombre) {
        initComponents();
        aux=raiz;
        nombreP="/";
        jPanel3.setLayout(null);
        pintarCarpetas(nombreP);
        this.usuario=nombre;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton11 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Crear");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Modificar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Eliminar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Subir");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel1.setText("Carpetas");

        jButton15.setText("Graficar");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });

        jButton16.setText("Grafo");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton15)
                    .addComponent(jButton16))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(19, 19, 19)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addGap(4, 4, 4)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton16)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton5.setText("Crear");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Modificar");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("Eliminar");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setText("Subir");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jLabel2.setText("Archivos");

        jButton11.setText("Ver");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jButton14.setText("Graficar");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton6)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(jButton11))
                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton14))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5)
                    .addComponent(jButton11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton14)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        jTextField1.setText("/");

        jButton9.setText("Entrar");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton10.setText("Ir");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jButton12.setText("Cerrar Sesion");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jButton13.setText("Compartir");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        jTextField2.setText("Ingrese usuario");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton12)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jButton13)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jButton12)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton13)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 455, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(14, 14, 14)
                                .addComponent(jButton10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton9, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE))
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton9)
                            .addComponent(jButton10))
                        .addGap(18, 18, 18)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        int contador=0;
        while(corX>100){
            corX=corX-101;
            contador+=1;
        }
        while(corY>50){
            corY=corY-60;
            contador+=6;
        }
        contador=contador-cantC;
        String sus=auxA[contador];
        int e=aux.buscar_fila(nombreP);
        String ArchivoNuevo = JOptionPane.showInputDialog("Escribe nombre del archivo");
        while(ArchivoNuevo.split("\\.").length!=2){
            ArchivoNuevo = JOptionPane.showInputDialog("Dato incoreccto");
        }
        if (aux.existe(aux.buscar_fila(e), ArchivoNuevo)) {
            if (sus.equals("/")||sus.equals("raiz")) {
            
            }else{
                //System.out.println(sus);
                int p=aux.buscar_fila(nombreP);
                aux.borrar(aux.buscar_fila(p), sus);
                jPanel3.removeAll();
                pintarCarpetas(nombreP);
            }
            
            Date date = new Date();
            DateFormat hourdateFormat = new SimpleDateFormat("HH:mm:ss dd/MM/yyyy");
            String time = "Hora y fecha: " + hourdateFormat.format(date);
            String[] parte = ArchivoNuevo.split("\\.");
            int p=aux.buscar_fila(nombreP);
            aux.agregarAVL(parte[0], jTextArea1.getText(), parte[1], time,aux.buscar_fila(p),usuario);
            pintarCarpetas(nombreP);
            bitacora.agregar(usuario, "Se  modifico el archivo "+ sus +"a "+ArchivoNuevo);
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String carpetaNueva = JOptionPane.showInputDialog("Escribe nombre de carpeta");
        Date date = new Date();
        DateFormat hourdateFormat = new SimpleDateFormat("HH:mm:ss dd/MM/yyyy");
        String time = "Hora y fecha: " + hourdateFormat.format(date);
        aux.insertar(new Carpeta(carpetaNueva,time),aux.buscar_fila(nombreP));
        pintarCarpetas(nombreP);
        aux.mostrar();
        bitacora.agregar(usuario, "Se crea la carpeta" + carpetaNueva);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        int contador=0;
        while(corX>100){
            corX=corX-101;
            contador+=1;
        }
        while(corY>50){
            corY=corY-60;
            contador+=6;
        }
        nombreP=auxC[contador];
        if (jTextField1.getText().equals("/")) {
            jTextField1.setText(jTextField1.getText()+nombreP);
        }else{
            jTextField1.setText(jTextField1.getText()+"/"+nombreP);
        }
        jPanel3.removeAll();
        pintarCarpetas(nombreP);
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        int contador=0;
        while(corX>100){
            corX=corX-101;
            contador+=1;
        }
        while(corY>50){
            corY=corY-60;
            contador+=6;
        }
        String sus=auxC[contador];
        if (sus.equals("/")||sus.equals("raiz")) {
            
        }else{
            System.out.println("borrar");
            aux.borrar(sus);
            jPanel3.removeAll();
            pintarCarpetas(nombreP);
            bitacora.agregar(usuario, "Se borro la  carpeta "+sus);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int contador=0;
        while(corX>100){
            corX=corX-101;
            contador+=1;
        }
        while(corY>50){
            corY=corY-60;
            contador+=6;
        }
        String sus=auxC[contador];
        if (sus.equals("/")||sus.equals("raiz")) {
            
        }else{
            System.out.println("modificar");
            String carpetaNueva = JOptionPane.showInputDialog("Escribe nombre de carpeta");
            aux.modificar(sus, carpetaNueva);
            jPanel3.removeAll();
            pintarCarpetas(nombreP);
            bitacora.agregar(usuario, "Se modifico la carpeta "+sus+" a"+ carpetaNueva);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        if (!jTextField1.getText().equals("/")) {
            String[] aux=jTextField1.getText().split("/");
            nombreP=aux[aux.length-1];
            jPanel3.removeAll();
            pintarCarpetas(nombreP);
        }else{
            nombreP="/";
            jPanel3.removeAll();
            pintarCarpetas(nombreP);
        }
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        String ArchivoNuevo = JOptionPane.showInputDialog("Escribe nombre del archivo");
        while(ArchivoNuevo.split("\\.").length!=2){
            ArchivoNuevo = JOptionPane.showInputDialog("Dato incoreccto");
        }
        Date date = new Date();
        DateFormat hourdateFormat = new SimpleDateFormat("HH:mm:ss dd/MM/yyyy");
        String time = "Hora y fecha: " + hourdateFormat.format(date);
        String[] parte = ArchivoNuevo.split("\\.");
        int p=aux.buscar_fila(nombreP);
        aux.agregarAVL(parte[0], jTextArea1.getText(), parte[1], time,aux.buscar_fila(p),usuario);
        pintarCarpetas(nombreP);
        bitacora.agregar(usuario, "Se creo el archivo "+ArchivoNuevo);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        int contador=0;
        while(corX>100){
            corX=corX-101;
            contador+=1;
        }
        while(corY>50){
            corY=corY-60;
            contador+=6;
        }
        contador=contador-cantC;
        String sus=auxA[contador];
        if (sus.equals("/")||sus.equals("raiz")) {
            
        }else{
            //System.out.println(sus);
            int p=aux.buscar_fila(nombreP);
            aux.borrar(aux.buscar_fila(p), sus);
            jPanel3.removeAll();
            pintarCarpetas(nombreP);
            bitacora.agregar(usuario, "Se elimino el archivo"+ sus);
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        int contador=0;
        while(corX>100){
            corX=corX-101;
            contador+=1;
        }
        while(corY>50){
            corY=corY-60;
            contador+=6;
        }
        contador=contador-cantC;
        String sus=auxA[contador];
        if (sus.equals("/")||sus.equals("raiz")) {
            
        }else{
            //System.out.println(sus);
            int p=aux.buscar_fila(nombreP);
            String con=aux.contenidoA(aux.buscar_fila(p), sus);
            jTextArea1.setText(con);
            jPanel3.removeAll();
            pintarCarpetas(nombreP);
        }
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        JFileChooser nuevo=new JFileChooser();
        nuevo.showOpenDialog(null);
        File abrir=null;
        String ruta="";
        try{
            abrir = nuevo.getSelectedFile();
        }catch(NullPointerException e){
            JOptionPane.showMessageDialog(null, "Seleccione un archivo .csv");
        }
        if (abrir!=null) {
            if (abrir.getName().endsWith(".csv")) {
                ruta=abrir.getPath();
            }else{
                JOptionPane.showMessageDialog(null, "Seleccione un archivo .csv");
            }
        }
        try {
            LeerArchivo(ruta);
        } catch (NoSuchAlgorithmException ex) {
            Logger.getLogger(Ventana.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        InicioSesion ini=new InicioSesion();
        ini.setVisible(true);
        ini.setLocationRelativeTo(null);
        dispose();
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        if (tablaha.recibir(jTextField2.getText())!=null) {
            int contador=0;
            while(corX>100){
                corX=corX-101;
                contador+=1;
            }
            while(corY>50){
                corY=corY-60;
                contador+=6;
            }
            contador=contador-cantC;
            String sus=auxA[contador];
            if (sus.equals("/")||sus.equals("raiz")) {

            }else{
                //System.out.println(sus);
                int p=aux.buscar_fila(nombreP);
                String nombre=aux.datos(aux.buscar_fila(p), sus);
                String part[]=nombre.split(";");
                int aux2=tablaha.recibir(jTextField2.getText()).buscar_fila("/");
                tablaha.recibir(jTextField2.getText()).agregarAVL(part[0], part[1], part[2], part[3], tablaha.recibir(jTextField2.getText()).buscar_fila(aux2),part[4]);
            }
        }else{
            JOptionPane.showMessageDialog(null, "Usuario no existe en el sistema");
        }
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        int p=aux.buscar_fila(nombreP);
        try {
            aux.grafo(aux.buscar_fila(p));
            ReporteArbol repA=new ReporteArbol();
            repA.setVisible(true);
        } catch (IOException ex) {
            Logger.getLogger(Ventana.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        try {
            aux.graficar();
            ReporteMatriz verM=new ReporteMatriz();
            verM.setVisible(true);
        } catch (IOException ex) {
            Logger.getLogger(Ventana.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        try {
            aux.grafoMamador();
            ReporteGrafo repoG=new ReporteGrafo();
            repoG.setVisible(true);
        } catch (IOException ex) {
            Logger.getLogger(Ventana.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton16ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
            }
        });
    }
    
    public void pintarCarpetas(String padre){
        int gX=0,gY=0;
        cantC=0;
        if (!aux.nombresC(padre).equals(" /;")&&!aux.nombresC(padre).equals("")) {
            jPanel3.removeAll();
            String[] partes=aux.nombresC(padre).split(";");
            JLabel[] labels=new JLabel[partes.length];
            int x=0;
            int y =0;
            cantC=partes.length;
            for (int i = 0; i < partes.length; i++) {
                labels[i]=new JLabel();
                if (partes[i]!=null && labels[i]!=null) {
                    //System.out.println("entra");
                    Image img= new ImageIcon(getClass().getResource("/Imagenes/carpeta.png")).getImage();
                    Image img2=img.getScaledInstance(40, 40, Image.SCALE_SMOOTH);
                    ImageIcon icon =new ImageIcon(img2);
                    //String path = "/Imagenes/carpeta.png";  
                    //URL url = this.getClass().getResource(path);  
                    //ImageIcon icon = new ImageIcon(url);  
                    labels[i].setIcon(icon);
                    labels[i].setText(partes[i]);
                    labels[i].setBounds(x,y,100,50);
                    labels[i].setVisible(true);
                    jPanel3.add(labels[i]); 
                    x+=101;
                    if (x>605) {
                        x=0;
                        y+=60;
                    }
                }
            }
            gX=x;
            gY=y;
            pintarArchivos(nombreP,gX,gY);
            jPanel3.repaint();
            auxC=partes;
        }else{
            jPanel3.removeAll();
            pintarArchivos(nombreP,gX,gY);
            jPanel3.repaint();
        }
        jPanel3.addMouseListener(new MouseListener() {
                        @Override
                        public void mouseClicked(MouseEvent e) {
                            corX =e.getPoint().x;
                            corY =e.getPoint().y;
                            //System.out.println(e.getPoint().x);
                            //System.out.println(e.getPoint().y);
                        }

                        @Override
                        public void mousePressed(MouseEvent e) {
                            
                        }

                        @Override
                        public void mouseReleased(MouseEvent e) {
                            
                        }

                        @Override
                        public void mouseEntered(MouseEvent e) {
                            
                        }

                        @Override
                        public void mouseExited(MouseEvent e) {
                            
                        }
                    });
    }
    
    public void pintarArchivos(String padre,int x,int y){
        int p=aux.buscar_fila(nombreP);
        if (!aux.nombresA(aux.buscar_fila(p)).equals("")) {
            String[] partes=aux.nombresA(aux.buscar_fila(p)).split(";");
            JLabel[] labels=new JLabel[partes.length];
            for (int i = 0; i < partes.length; i++) {
                labels[i]=new JLabel();
                if (partes[i]!=null && labels[i]!=null) {
                    //System.out.println("entraArchivo");
                    Image img= new ImageIcon(getClass().getResource("/Imagenes/logo.png")).getImage();
                    Image img2=img.getScaledInstance(40, 40, Image.SCALE_SMOOTH);
                    ImageIcon icon =new ImageIcon(img2);
                    //String path = "/Imagenes/carpeta.png";  
                    //URL url = this.getClass().getResource(path);  
                    //ImageIcon icon = new ImageIcon(url);  
                    labels[i].setIcon(icon);
                    labels[i].setText(partes[i]);
                    labels[i].setBounds(x,y,100,50);
                    labels[i].setVisible(true);
                    jPanel3.add(labels[i]); 
                    x+=101;
                    if (x>605) {
                        x=0;
                        y+=60;
                    }
                }
            }
            auxA=partes;
        }
    
    }
    public String LeerArchivo(String rutaArchivo) throws NoSuchAlgorithmException {
        try {
            FileReader fr = new FileReader(rutaArchivo);
            BufferedReader br = new BufferedReader(fr);
            String Fila="";
            String Resultado="";
            boolean primeraU=false;
            Fila=br.readLine();
            if (Fila.split(",",2)[0].equalsIgnoreCase("archivo")) {
                    primeraU= true;
            }
            while((Fila=br.readLine())!=null){
                if (primeraU) {
                    Date date = new Date();
                    DateFormat hourdateFormat = new SimpleDateFormat("HH:mm:ss dd/MM/yyyy");
                    String time = "Hora y fecha: " + hourdateFormat.format(date);
                    String[] parte = Fila.split(",",2)[0].split("\\.");
                    int p=aux.buscar_fila(nombreP);
                    aux.agregarAVL(parte[0], Fila.split(",",2)[1].replace("\"", ""), parte[1], time,aux.buscar_fila(p),usuario);
                    pintarCarpetas(nombreP);
                    bitacora.agregar(usuario, "Se creo el archivo "+Fila.split(",",2)[0]);
                }else{
                    Date date = new Date();
                    DateFormat hourdateFormat = new SimpleDateFormat("HH:mm:ss dd/MM/yyyy");
                    String time = "Hora y fecha: " + hourdateFormat.format(date);
                    String[] parte = Fila.split(",",2)[1].split("\\.");
                    int p=aux.buscar_fila(nombreP);
                    aux.agregarAVL(parte[0], Fila.split(",",2)[0].replace("\"", ""), parte[1], time,aux.buscar_fila(p),usuario);
                    pintarCarpetas(nombreP);
                    bitacora.agregar(usuario, "Se creo el archivo "+Fila.split(",",2)[1]);
                }
            }
            return Resultado;
            
        } catch (FileNotFoundException ex) {
            return ex.getMessage();
        } catch (IOException ex) {
            return ex.getMessage();
        }
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
